### ISSUE TITLE
Linux error

### ISSUE THREAD

**Issue by kaiserdj** [alvin-777/flash-player-loader-for-electron#4]
The module works perfectly on windows and mac, the only problem is linux (I tried it on ubuntu). Does not load the plugin:
![image](https://user-images.githubusercontent.com/5487950/104956734-0612df80-59cd-11eb-9a80-373c56578caf.png)

Files that I have used for the test:
[test.zip](https://github.com/alvin-777/flash-player-loader-for-electron/files/5832124/test.zip)

**Comment by alvin-777** [comment]
Flash is End-Of-Life and will be no longer supported by Adobe ([link](https://www.adobe.com/products/flashplayer/end-of-life.html))

Continue using flash is not considered secure and is **strongly discouraged**.

Therefore, this project will no longer be maintained and updated. I'm sorry.

----
There're a couple of advices that you can give a try though:
- Check your electron, make sure it's 64-bit (I see the attached flash is 64-bit)
- When specifying the path to flash file, leave the version string out:
  `flashLoader.addSource(pathToDirContainsFlashPlayer, '29.0.0.171');` => `flashLoader.addSource(pathToDirContainsFlashPlayer);`
